name: Deploy Hugo Site

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy-prod:
    name: "Deploy to Rakhama.com"
    runs-on: ubuntu-latest
    environment:
      name: Rakhama.com
      url: https://rakhama.com
    env:
      DEPLOY_SOURCE: "public"

    steps:
      - uses: actions/checkout@v2

      - name: Clear destination directory
        uses: fifsky/ssh-action@v0.0.6
        with:
          command: "rm -rf ${{ secrets.DEPLOY_DIRECTORY }}/"
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          
      - name: SCP Files
        uses: nogsantos/scp-deploy@master
        with:
          src: ${{ env.DEPLOY_SOURCE }}/*
          host: ${{ secrets.DEPLOY_HOST }}
          remote: ${{ secrets.DEPLOY_DIRECTORY }}
          port: ${{ secrets.DEPLOY_PORT }}
          user: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
